// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://eshjpvlafdpzobmjlcfv.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaGpwdmxhZmRwem9ibWpsY2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwMjY4NzEsImV4cCI6MjA0ODYwMjg3MX0.G3ivWcT7D0f2QJx2B86sHDFjNnomszIkHYnqre0ZYA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);