// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://matglrypqhmfvcbgjegy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdGdscnlwcWhtZnZjYmdqZWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzODI3MjksImV4cCI6MjA0Nzk1ODcyOX0.-1NXR9YhXklDSgca2hE5He3_cUYbO5q-UC5WOSBwywk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);